eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurantdb
    username: root
    password: Buddha@123
    driver-class-name: com.mysql.cj.jdbc.Driver